### ISSUE TITLE
is it possible to move it to pat-base

### ISSUE THREAD

**Issue by iham** [it-spirit/collective.tiles.sliders#1]
"Usage of the mockup-patterns-base pattern is deprecated and it will eventually be removed.Instead, use pat-base and explicitly set parser to 'mockup' when calling extend."

update this?

**Comment by thomasmassmann** [comment]
Sure, any contribution is more than welcome.

**Comment by iham** [comment]
i forked it to the collective to add changes. more soon.

q: can you make me a maintainer on pypi? (iham is my acc there)
q: maybe lets think about moving to collective?

**Comment by thomasmassmann** [comment]
Closed as being developed now in collective.
